//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./api_types');
//HELPER FUNCTIONS AND STRUCTURES

var userService_py_gen_ph_args = function(args) {
  this.dic = null;
  if (args) {
    if (args.dic !== undefined && args.dic !== null) {
      this.dic = args.dic;
    }
  }
};
userService_py_gen_ph_args.prototype = {};
userService_py_gen_ph_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.dic = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

userService_py_gen_ph_args.prototype.write = function(output) {
  output.writeStructBegin('userService_py_gen_ph_args');
  if (this.dic !== null && this.dic !== undefined) {
    output.writeFieldBegin('dic', Thrift.Type.STRING, 1);
    output.writeString(this.dic);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var userService_py_gen_ph_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
userService_py_gen_ph_result.prototype = {};
userService_py_gen_ph_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

userService_py_gen_ph_result.prototype.write = function(output) {
  output.writeStructBegin('userService_py_gen_ph_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var userService_clear_args = function(args) {
};
userService_clear_args.prototype = {};
userService_clear_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

userService_clear_args.prototype.write = function(output) {
  output.writeStructBegin('userService_clear_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var userService_clear_result = function(args) {
};
userService_clear_result.prototype = {};
userService_clear_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

userService_clear_result.prototype.write = function(output) {
  output.writeStructBegin('userService_clear_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var userServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
userServiceClient.prototype = {};
userServiceClient.prototype.seqid = function() { return this._seqid; };
userServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

userServiceClient.prototype.py_gen_ph = function(dic, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_py_gen_ph(dic);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_py_gen_ph(dic);
  }
};

userServiceClient.prototype.send_py_gen_ph = function(dic) {
  var output = new this.pClass(this.output);
  var params = {
    dic: dic
  };
  var args = new userService_py_gen_ph_args(params);
  try {
    output.writeMessageBegin('py_gen_ph', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

userServiceClient.prototype.recv_py_gen_ph = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new userService_py_gen_ph_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('py_gen_ph failed: unknown result');
};

userServiceClient.prototype.clear = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_clear();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_clear();
  }
};

userServiceClient.prototype.send_clear = function() {
  var output = new this.pClass(this.output);
  var args = new userService_clear_args();
  try {
    output.writeMessageBegin('clear', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

userServiceClient.prototype.recv_clear = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new userService_clear_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
var userServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
userServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
userServiceProcessor.prototype.process_py_gen_ph = function(seqid, input, output) {
  var args = new userService_py_gen_ph_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.py_gen_ph.length === 1) {
    Q.fcall(this._handler.py_gen_ph.bind(this._handler),
      args.dic
    ).then(function(result) {
      var result_obj = new userService_py_gen_ph_result({success: result});
      output.writeMessageBegin("py_gen_ph", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("py_gen_ph", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.py_gen_ph(args.dic, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new userService_py_gen_ph_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("py_gen_ph", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("py_gen_ph", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
userServiceProcessor.prototype.process_clear = function(seqid, input, output) {
  var args = new userService_clear_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.clear.length === 0) {
    Q.fcall(this._handler.clear.bind(this._handler)
    ).then(function(result) {
      var result_obj = new userService_clear_result({success: result});
      output.writeMessageBegin("clear", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("clear", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.clear(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new userService_clear_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("clear", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("clear", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
